sudo: required
services:
  - docker

before_install:
  - docker build -t luangonzalez/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luangonzalez/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-720133463622"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: "$access_key_id"
  secret_access_key: 
    secure: "$secret_access_key"