version: '3'

services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    ports:
        - "3000:3000"
    volumes:
        - /app/node_modules #makes this volder don`t be mapped because overviders the below mapping
        - .:/app
  tests:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #makes this volder don`t be mapped because overviders the below mapping
      - .:/app
    command: ["npm", "run", "test"]